name: Build And Publish Download Manager

on:
  push:
    branches: [ "multipart" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Download Dependencies
      run: go mod download

    - name: Tidy Dependencies
      run: go mod tidy

    - name: Build
      run: go build -o ./download-manager -gcflags=-trimpath=$GOPATH -asmflags=-trimpath=$GOPATH

    - name: Make it executable
      run: chmod +x ./download-manager
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with: 
        name: download-manager
        path: ./download-manager
        retention-days: 14
